#!/usr/bin/env node
// Build assets/styles/fonts.css with base64-embedded woff2 @font-face rules.
// Base64 embedding (not @font-face URLs) is what makes headless Chrome screenshots
// deterministic: the glyphs are present synchronously, so there is no font-load race
// that would screenshot a fallback face. Re-run only when the woff2 files change.
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const fontsDir = join(here, "..", "assets", "fonts");
const out = join(here, "..", "assets", "styles", "fonts.css");

const families = {
  "plus-jakarta-sans": "Plus Jakarta Sans",
  "jetbrains-mono": "JetBrains Mono",
};

const files = readdirSync(fontsDir).filter((f) => f.endsWith(".woff2"));
let css = "/* AUTO-GENERATED by scripts/build-fonts.mjs — do not edit by hand. */\n";

for (const file of files.sort()) {
  const m = file.match(/^(.*)-(\d{3})\.woff2$/);
  if (!m) continue;
  const [, slug, weight] = m;
  const family = families[slug];
  if (!family) continue;
  const b64 = readFileSync(join(fontsDir, file)).toString("base64");
  css += `@font-face{font-family:'${family}';font-style:normal;font-weight:${weight};font-display:block;src:url(data:font/woff2;base64,${b64}) format('woff2');}\n`;
}

writeFileSync(out, css);
console.log(`Wrote ${out} (${(css.length / 1024).toFixed(0)} KB) from ${files.length} woff2 files`);
